window.rldState = window.rldState || { rows: [], selected: new Set() };

function rldDomains(){return [...document.querySelectorAll('.rld-domain:checked')].map(x=>x.value)}
function rldSelectAll(value){document.querySelectorAll('.rld-domain').forEach(x=>x.checked=value)}
function rldEscape(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function rldSetBusy(value){document.getElementById('rldOverlay').style.display=value?'flex':'none';document.getElementById('rldRunButton').disabled=value}
async function rldApi(action,payload={}){const response=await fetch(`/module/relatorio-limite-destinatarios/api?action=${encodeURIComponent(action)}&_=${Date.now()}`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const text=await response.text();let data=JSON.parse(text);if(typeof data==='string')data=JSON.parse(data);if(!response.ok||!data.success)throw new Error(data.message||data.error||`Erro HTTP ${response.status}`);return data}

async function rldConnect(){document.getElementById('rldStatus').textContent='A abrir autenticação do Exchange Online...';try{await conectarExchangeGlobal();document.getElementById('rldStatus').textContent='Exchange Online conectado. Pode gerar o relatório.'}catch(e){document.getElementById('rldStatus').textContent=`Falha na ligação: ${e.message}`}}
async function rldRun(){const domains=rldDomains();if(!domains.length){alert('Selecione pelo menos um domínio.');return}const mailboxType=document.getElementById('rldMailboxType')?.value||'all',limitMode=document.getElementById('rldLimitMode')?.value||'all',limitValue=document.getElementById('rldLimitValue')?.value||'';if(limitMode==='exact'&&(!/^\d+$/.test(limitValue)||Number(limitValue)<1)){alert('Indique uma quantidade de limite válida.');return}const progress=document.getElementById('rldLiveProgress'),started=Date.now();window.rldState.rows=[];rldRender();rldSetBusy(false);document.getElementById('rldRunButton').disabled=true;progress.hidden=false;document.getElementById('rldStatus').textContent='A consultar no Exchange apenas os filtros selecionados...';try{const response=await fetch(`/module/relatorio-limite-destinatarios/api?action=consultar-stream&stream=true&_=${Date.now()}`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({domains,mailboxType,limitMode,limitValue})});if(!response.ok||!response.body)throw new Error(`Erro HTTP ${response.status}`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const part=await reader.read();buffer+=decoder.decode(part.value||new Uint8Array(),{stream:!part.done});const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines){if(line.trim())rldStreamEvent(JSON.parse(line),started,domains)}if(part.done)break}if(buffer.trim())rldStreamEvent(JSON.parse(buffer),started,domains)}catch(e){document.getElementById('rldStatus').textContent=`Erro: ${e.message}`;alert(e.message)}finally{document.getElementById('rldRunButton').disabled=false;setTimeout(()=>progress.hidden=true,1200)}}
function rldStreamEvent(event,started,domains){if(event.type==='error'||event.success===false)throw new Error(event.message||'Falha na consulta.');if(event.type==='batch'){window.rldState.rows.push(...(event.rows||[]));rldRender()}const seconds=Math.max(1,Math.round((Date.now()-started)/1000));if(event.type==='progress'||event.type==='batch'){document.getElementById('rldProgressText').textContent=`${event.scanned||0} caixas analisadas • ${event.found||0} encontradas • ${seconds}s decorridos`;document.getElementById('rldResultInfo').textContent=`A receber resultados: ${event.found||0} caixa(s) encontradas.`}if(event.type==='complete'){window.rldState.rows.sort((a,b)=>(a.domain+a.primarySmtpAddress).localeCompare(b.domain+b.primarySmtpAddress));rldRender();document.getElementById('rldProgressText').textContent=`Concluído: ${event.scanned} analisadas e ${event.found} encontradas em ${seconds}s.`;document.getElementById('rldResultInfo').textContent=`${event.found} caixa(s) nos domínios ${domains.map(x=>'@'+x).join(' e ')}.`;document.getElementById('rldStatus').textContent=`Consulta concluída em ${event.generatedAt||''}.`}}
function rldLimitModeChanged(){const exact=document.getElementById('rldLimitMode').value==='exact';document.getElementById('rldLimitValueWrap').hidden=!exact;rldRender()}
function rldFiltered(){const q=(document.getElementById('rldSearch')?.value||'').trim().toLowerCase();const mailboxType=document.getElementById('rldMailboxType')?.value||'all';const mode=document.getElementById('rldLimitMode')?.value||'all';const exact=String(parseInt(document.getElementById('rldLimitValue')?.value||'',10));return window.rldState.rows.filter(r=>{const textOk=!q||[r.displayName,r.primarySmtpAddress,r.domain,r.recipientTypeDetails,r.recipientLimit].some(v=>String(v||'').toLowerCase().includes(q));const typeOk=mailboxType==='all'||r.recipientTypeDetails===mailboxType;const limit=String(r.recipientLimit||'');const limitOk=mode==='all'||(mode==='unlimited'&&r.status==='Sem limite')||(mode==='exact'&&exact!=='NaN'&&limit===exact);return textOk&&typeOk&&limitOk})}
function rldRender(){const rows=rldFiltered(),body=document.getElementById('rldTable');rldKpis(rldSummary(rows));if(!rows.length){body.innerHTML='<tr><td colspan="8" class="rld-empty">Nenhuma caixa corresponde aos filtros selecionados.</td></tr>';rldUpdateSelection();return}body.innerHTML=rows.map(r=>{const cls=r.status==='Sem limite'?'rld-unlimited':r.status==='Limite 50'?'rld-ok':'rld-warning',address=String(r.primarySmtpAddress||''),encoded=encodeURIComponent(address);return `<tr><td><input type="checkbox" ${window.rldState.selected.has(address)?'checked':''} onchange="rldToggleOne(decodeURIComponent('${encoded}'),this.checked)" aria-label="Selecionar ${rldEscape(address)}"></td><td>${rldEscape(r.displayName)}</td><td>${rldEscape(address)}</td><td>@${rldEscape(r.domain)}</td><td>${rldEscape(r.recipientTypeDetails)}</td><td><strong>${rldEscape(r.recipientLimit)}</strong></td><td><span class="rld-badge ${cls}">${rldEscape(r.status)}</span></td><td><button class="rld-row-action" type="button" onclick="rldOpenServiceNowOne(decodeURIComponent('${encoded}'))">Alterar + ticket</button></td></tr>`}).join('');rldUpdateSelection()}
function rldSummary(rows){return{total:rows.length,limit50:rows.filter(r=>r.status==='Limite 50').length,otherLimits:rows.filter(r=>r.status==='Outro limite').length,unlimited:rows.filter(r=>r.status==='Sem limite').length}}
function rldToggleOne(address,checked){checked?window.rldState.selected.add(address):window.rldState.selected.delete(address);rldUpdateSelection()}
function rldToggleVisible(checked){rldFiltered().forEach(r=>checked?window.rldState.selected.add(r.primarySmtpAddress):window.rldState.selected.delete(r.primarySmtpAddress));rldRender()}
function rldSelectedRows(){return window.rldState.rows.filter(r=>window.rldState.selected.has(r.primarySmtpAddress))}
function rldUpdateSelection(){const count=window.rldState.selected.size,info=document.getElementById('rldSelectionInfo');if(info)info.textContent=count?`${count} caixa(s) selecionada(s).`:'Nenhuma caixa selecionada.';const all=document.getElementById('rldSelectAll'),visible=rldFiltered();if(all){all.checked=visible.length>0&&visible.every(r=>window.rldState.selected.has(r.primarySmtpAddress));all.indeterminate=visible.some(r=>window.rldState.selected.has(r.primarySmtpAddress))&&!all.checked}}
async function rldApplyLimit(){const rows=rldSelectedRows(),limit=Number(document.getElementById('rldNewLimit')?.value);if(!rows.length){alert('Selecione pelo menos uma caixa.');return}if(!Number.isInteger(limit)||limit<1||limit>1000){alert('O limite deve ser um número entre 1 e 1000.');return}if(!confirm(`Confirma a alteração de ${rows.length} caixa(s) para o limite ${limit}?`))return;rldSetBusy(true);try{const result=await rldApi('aplicar-limite',{identities:rows.map(r=>r.primarySmtpAddress),limit});const success=new Set((result.updated||[]).map(x=>x.identity));window.rldState.rows.forEach(r=>{if(success.has(r.primarySmtpAddress)){r.recipientLimit=String(limit);r.status=limit===50?'Limite 50':'Outro limite'}});rldRender();alert(`${result.updated.length} caixa(s) atualizada(s).${result.failed.length?`\n${result.failed.length} falha(s).`:''}`)}catch(e){alert(e.message)}finally{rldSetBusy(false)}}
const RLD_MAIL_TO='rldApprovalTo',RLD_MAIL_CC='rldApprovalCc';
function rldOpenApproval(){const rows=rldSelectedRows(),limit=document.getElementById('rldNewLimit')?.value||'1000';if(!rows.length){alert('Selecione pelo menos uma caixa para incluir no pedido.');return}document.getElementById('rldApprovalTo').value=localStorage.getItem(RLD_MAIL_TO)||'';document.getElementById('rldApprovalCc').value=localStorage.getItem(RLD_MAIL_CC)||'';document.getElementById('rldApprovalSubject').value=`Pedido de aprovação - alteração de limite de destinatários para ${limit}`;document.getElementById('rldApprovalSummary').innerHTML=`<strong>Novo limite:</strong> ${rldEscape(limit)}<br><strong>Caixas:</strong> ${rows.length}<br>${rows.slice(0,8).map(r=>rldEscape(r.primarySmtpAddress)).join('<br>')}${rows.length>8?`<br>... e mais ${rows.length-8}`:''}`;document.getElementById('rldApprovalModal').hidden=false}
function rldCloseApproval(){document.getElementById('rldApprovalModal').hidden=true}
function rldSaveMailPrefs(){localStorage.setItem(RLD_MAIL_TO,document.getElementById('rldApprovalTo').value||'');localStorage.setItem(RLD_MAIL_CC,document.getElementById('rldApprovalCc').value||'')}
async function rldPrepareApprovalEmail(){const rows=rldSelectedRows(),limit=Number(document.getElementById('rldNewLimit')?.value),to=document.getElementById('rldApprovalTo').value.trim(),cc=document.getElementById('rldApprovalCc').value.trim(),subject=document.getElementById('rldApprovalSubject').value.trim();if(!to){alert('Informe pelo menos um destinatário.');return}rldSaveMailPrefs();try{const result=await rldApi('preparar-aprovacao',{to,cc,subject,limit,mailboxes:rows});rldCloseApproval();alert(result.message||'Email preparado no Outlook.')}catch(e){alert(e.message)}}
document.addEventListener('input',e=>{if(e.target?.id==='rldApprovalTo'||e.target?.id==='rldApprovalCc')rldSaveMailPrefs()});
const RLD_SERVICENOW_URL='https://santander.service-now.com/itsm?id=sc_cat_item&sys_id=3bb85467db79c0d4f1024dc2ba961997&sysparm_category=93d369bedbf1a700ec3fa5305b96190a';
function rldServiceNowText(row,desired,previous){return ['PEDIDO DE ALTERAÇÃO - LIMITE DE DESTINATÁRIOS','',`Data: ${new Date().toLocaleString('pt-PT')}`,`Mailbox: ${row.primarySmtpAddress}`,`Nome: ${row.displayName||'-'}`,`Tipo: ${row.recipientTypeDetails||'-'}`,`Limite anterior: ${previous||'-'}`,`Novo limite aplicado: ${desired}`,'','A configuração foi atualizada no Exchange Online.','Origem: Relatório Limites de Destinatários - Santander Support Web V2'].join('\n')}
function rldStartClipboardCopy(text){let legacy=false;try{const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.left='-10000px';area.style.top='0';document.body.appendChild(area);area.focus();area.select();legacy=document.execCommand('copy');area.remove()}catch{}const modern=navigator.clipboard?.writeText?navigator.clipboard.writeText(text).then(()=>true).catch(()=>false):Promise.resolve(false);return{legacy,modern}}
async function rldOpenServiceNowOne(address){const row=window.rldState.rows.find(r=>r.primarySmtpAddress===address),limit=Number(document.getElementById('rldNewLimit')?.value);if(!row)return;if(!Number.isInteger(limit)||limit<1||limit>1000){alert('Informe um novo limite entre 1 e 1000.');return}if(!confirm(`Alterar ${address} para o limite ${limit} e abrir o ServiceNow?`))return;const previous=row.recipientLimit,text=rldServiceNowText(row,limit,previous),copy=rldStartClipboardCopy(text),popup=window.open('about:blank','_blank');if(!popup){alert('O navegador bloqueou o ServiceNow. Autorize popups e tente novamente.');return}try{popup.document.title='Santander Support Web V2';popup.document.body.innerHTML='<p style="font:16px Segoe UI;padding:30px">A alterar a configuração no Exchange Online...</p>';popup.opener=null}catch{}try{const result=await rldApi('aplicar-limite',{identities:[address],limit});if(!(result.updated||[]).some(x=>x.identity===address)){throw new Error(result.failed?.[0]?.error||'O Exchange não confirmou a alteração.')}row.recipientLimit=String(limit);row.status=limit===50?'Limite 50':'Outro limite';rldRender();const copied=copy.legacy||await copy.modern;if(!copied)window.prompt('Copie este texto antes de continuar para o ServiceNow:',text);popup.location.href=RLD_SERVICENOW_URL;alert(copied?'Limite alterado no Exchange. Use Ctrl+V no campo de descrição do ServiceNow.':'Limite alterado. O texto foi apresentado para cópia manual.')}catch(e){try{popup.close()}catch{}alert(`A configuração não foi alterada e o ServiceNow não foi aberto.\n\n${e.message}`)}}
function rldKpis(s){document.getElementById('rldTotal').textContent=s.total||0;document.getElementById('rld50').textContent=s.limit50||0;document.getElementById('rldOther').textContent=s.otherLimits||0;document.getElementById('rldUnlimited').textContent=s.unlimited||0}
function rldExportCsv(){const rows=rldFiltered();if(!rows.length){alert('Não existem dados para exportar.');return}const headers=['Nome','EnderecoPrincipal','Dominio','TipoCaixa','LimiteDestinatarios','Estado'];const values=rows.map(r=>[r.displayName,r.primarySmtpAddress,r.domain,r.recipientTypeDetails,r.recipientLimit,r.status]);const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\ufeff'+[headers,...values].map(row=>row.map(quote).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Limites_Destinatarios_${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
